name: Renovate depedency check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # Run daily at 2 AM UTC

jobs:
  renovate:
    permissions:
        contents: write
        pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.RENOVATE_APP_ID }}
          private_key: ${{ secrets.RENOVATE_PRIVATE_KEY }}
      - name: Run Renovate
        uses: renovatebot/github-action@e2421a9a80287bba9997b41a15ea1e5585d96925 # v43.0.16
        with:
          token: ${{ steps.app-token.outputs.token }}
        env:
          LOG_LEVEL: DEBUG
          RENOVATE_REPOSITORIES: 'thanh-ngvt/renovate-test'
